param(
    [Parameter(Position = 0)]
    [ValidateSet("status", "auth-only", "none", "freesia", "freesia-fixture", "fixture", "generated", "paper-generated", "paper", "raw-replay", "bootstrap")]
    [string]$Mode = "status",

    [string]$Model = "saved",
    [string]$Capture = "freesia-from-velocity",
    [string]$TokenSalt = "",
    [ValidateSet("openysm", "legacy", "keys")]
    [string]$GeneratedLayout = "openysm",
    [ValidateSet("server-cache", "washed-zstd", "headerless-v3", "encrypted-v3")]
    [string]$GeneratedPayload = "server-cache",
    [int]$IntervalTicks = 0,
    [int]$ChunkBytes = 0,
    [switch]$FreshToken,
    [switch]$ResetPlayerModels,
    [switch]$NoBackup
)

$ErrorActionPreference = "Stop"

function Write-Utf8NoBomCrLf {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,
        [Parameter(Mandatory = $true)]
        [string]$Text
    )
    $normalized = $Text -replace "`r?`n", "`r`n"
    [System.IO.File]::WriteAllText($Path, $normalized, [System.Text.UTF8Encoding]::new($false))
}

function Bool-Text {
    param([bool]$Value)
    if ($Value) { "true" } else { "false" }
}

function Show-Status {
    param([string]$ConfigPath)
    if (!(Test-Path -LiteralPath $ConfigPath)) {
        Write-Host "PaperYSM direct config is missing: $ConfigPath"
        return
    }
    Write-Host "Direct PaperYSM config:"
    Write-Host "  $ConfigPath"
    Select-String -LiteralPath $ConfigPath -Pattern "models-dir|enable-raw-replay|auto-native-cache|auto-generated-cache|experimental-bootstrap|remember-player-models|saved-models-file" |
        ForEach-Object { Write-Host ("  " + $_.Line.Trim()) }
}

$root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$dataDir = Join-Path $root "test-server\direct-paper\plugins\PaperYSM"
$configPath = Join-Path $dataDir "config.yml"

if ($Mode -eq "status") {
    Show-Status $configPath
    exit 0
}

New-Item -ItemType Directory -Force -Path $dataDir | Out-Null

$modeKey = $Mode.ToLowerInvariant()
if ($modeKey -eq "freesia-fixture") {
    $modeKey = "freesia"
}
if ($modeKey -eq "fixture") {
    $modeKey = "freesia"
}
if ($modeKey -eq "paper-generated") {
    $modeKey = "generated"
}
if ($modeKey -eq "paper") {
    $modeKey = "generated"
}
if ($modeKey -eq "none") {
    $modeKey = "auth-only"
}

$enableRawReplay = $false
$autoNative = $false
$autoGenerated = $false
$experimentalBootstrap = $false
$rawInterval = 2
$nativeInterval = 1
$nativeChunk = 59926
$generatedInterval = 1
$generatedChunk = 24576
$bootstrapMode = "zero"
$writeCacheFiles = $false

switch ($modeKey) {
    "auth-only" {
        $profileName = "auth-only"
    }
    "freesia" {
        $profileName = "freesia-fixture"
        $autoNative = $true
    }
    "generated" {
        $profileName = "paper-generated"
        $autoGenerated = $true
    }
    "raw-replay" {
        $profileName = "raw-replay"
        $enableRawReplay = $true
    }
    "bootstrap" {
        $profileName = "bootstrap-probe"
        $experimentalBootstrap = $true
    }
    default {
        throw "Unsupported mode: $Mode"
    }
}

if ($IntervalTicks -gt 0) {
    if ($modeKey -eq "freesia") {
        $nativeInterval = $IntervalTicks
    } elseif ($modeKey -eq "generated") {
        $generatedInterval = $IntervalTicks
    } else {
        $rawInterval = $IntervalTicks
    }
}

if ($ChunkBytes -gt 0) {
    if ($modeKey -eq "freesia") {
        $nativeChunk = $ChunkBytes
    } elseif ($modeKey -eq "generated") {
        $generatedChunk = $ChunkBytes
    }
}

$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
if ($FreshToken -and [string]::IsNullOrWhiteSpace($TokenSalt)) {
    $TokenSalt = $timestamp
}

if ((Test-Path -LiteralPath $configPath) -and !$NoBackup) {
    Copy-Item -LiteralPath $configPath -Destination "$configPath.bak-$timestamp" -Force
}

if ($ResetPlayerModels) {
    $savedModels = Join-Path $dataDir "player-models.yml"
    if (Test-Path -LiteralPath $savedModels) {
        Move-Item -LiteralPath $savedModels -Destination "$savedModels.bak-$timestamp" -Force
        Write-Host "Backed up player model state:"
        Write-Host "  $savedModels.bak-$timestamp"
    }
}

$config = @"
# Generated by scripts/switch-direct-paper-channel.ps1 profile=$profileName
# Direct Paper is the primary PaperYSM test server. Velocity/FreesiaII remains
# a comparison stack for protocol capture, not the normal PaperYSM runtime.
protocol-version: "2.6.0"
channel: "yes_steve_model:2_6_0"

handshake-delay-ticks: 20
handshake-retries: 2
handshake-retry-interval-ticks: 60

debug: false

logging:
  model-scan-details: false
  packet-details: false
  progress-interval-models: 32
  packet-hex-preview-bytes: 96
  raw-packet-hex-preview-bytes: 128

models-dir: "models"
scan-models-on-enable: true

state:
  remember-player-models: true
  saved-models-file: "player-models.yml"

distribution:
  prepare-on-reload: false
  chunk-bytes: 24576
  cache-dir: "cache/openysm/distribution"
  write-cache-files: $(Bool-Text $writeCacheFiles)

sync:
  send-authorized-models-on-handshake: true
  warn-missing-native-sync-on-handshake: true
  enable-raw-replay: $(Bool-Text $enableRawReplay)
  raw-replay-dir: "debug/replay"
  raw-replay-interval-ticks: $rawInterval
  raw-replay-handshake-timeout-ticks: 1500
  auto-native-cache-on-handshake: $(Bool-Text $autoNative)
  auto-native-cache-capture: "$Capture"
  auto-native-cache-delay-ticks: 20
  auto-native-cache-interval-ticks: $nativeInterval
  auto-native-cache-chunk-bytes: $nativeChunk
  auto-generated-cache-on-handshake: $(Bool-Text $autoGenerated)
  auto-generated-cache-model: "$Model"
  auto-generated-cache-delay-ticks: 20
  auto-generated-cache-interval-ticks: $generatedInterval
  auto-generated-cache-chunk-bytes: $generatedChunk
  auto-generated-cache-max-models: 32
  auto-generated-cache-type5-packets-per-tick: 2
  auto-generated-cache-prewarm-on-startup: false
  auto-generated-cache-prewarm-model: "all"
  auto-generated-cache-prewarm-delay-ticks: 1200
  auto-generated-cache-sync-online-after-prewarm: false
  auto-generated-cache-layout: "$GeneratedLayout"
  auto-generated-cache-payload: "$GeneratedPayload"
  auto-generated-cache-token-salt: "$TokenSalt"
  experimental-bootstrap-on-handshake: $(Bool-Text $experimentalBootstrap)
  experimental-bootstrap-mode: "$bootstrapMode"
  experimental-probe-interval-ticks: 8

capture:
  client-raw-packets: false
  raw-packet-dir: "debug/raw-packets"

native:
  enabled: false
  mode: "java"
"@

Write-Utf8NoBomCrLf -Path $configPath -Text $config

Write-Host "Switched direct PaperYSM channel profile: $profileName"
Write-Host "Config:"
Write-Host "  $configPath"
Write-Host "Restart scripts\start-direct-paper.bat for the change to take effect."
if ($modeKey -eq "generated" -and ![string]::IsNullOrWhiteSpace($TokenSalt)) {
    Write-Host "Generated cache token salt:"
    Write-Host "  $TokenSalt"
}
if ($modeKey -eq "generated") {
    Write-Host "Generated cache layout:"
    Write-Host "  $GeneratedLayout"
    Write-Host "Generated cache payload:"
    Write-Host "  $GeneratedPayload"
}
Show-Status $configPath
